### ISSUE TITLE
Building on ARM64 architecture

### ISSUE THREAD

**Issue by Deltaus** [wolfgangbrandl/db2_fdw#43]
Hi, I'm just wondering if it's possible to install this extension on an arm(aarch)64 platform? It looks like IBM db2 client doesn't support this architecture yet. (maybe it doesn't make sense to do it since all users of db2 will be on other OS arch......)

**Comment by wolfgangbrandl** [comment]
HiYou Need a db2 Definition of the database and the node if it is remote.That you can only achieve with a db2 installation. For compiling you need the db2 libraries, also only in an db2 installation image available.RegardsWolfgangVon meinem iPhone gesendetAm 21.09.2023 um 18:07 schrieb Derek ***@***.***>:﻿
Hi, I'm just wondering if it's possible to install this extension on an arm(aarch)64 platform? It looks like IBM db2 client doesn't support this architecture yet. (maybe it doesn't make sense to do it since all users of db2 will be on other OS arch......)
